apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-scale-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: test-scale-sa # defined in service-account.yaml