apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: test-scale-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginxpod
          image: nginx
          ports:
            - containerPort: 80
